numbers = [1, 2, 3, 4, 5]
letters = ["a", "b", "c", "d", "e"]
words = ["Sir", "Kei", "Murphy", "Licántropo"]
booleans = [True, False, True, False, False]
matrix = [[1, 2, 3, 4, 5], [5, 4, 3, 2, 1]]
ceros = [0] * 10
alfanumeric = numbers + letters
rang = list(range(1, 11))
chars = list("Hello")
